apiVersion: v1
kind: Service
metadata:
  name: energy-prediction-server
spec:
  type: NodePort
  selector:
    app: energy-prediction-server
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080