apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect
  labels:
    app: prefect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect
  template:
    metadata:
      labels:
        app: prefect
    spec:
      containers:
        - name: prefect
          image: prefecthq/prefect:3-latest
          command: ["prefect", "server", "start", "--host", "0.0.0.0"]
          ports:
            - containerPort: 4200
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"