name: CI/CD Docker to App Runner

on:
  push:
    branches:
      - main  # deploy on main branch push
    paths:
      - "midterm-project/**"
      - "!midterm-project/**/*.ipynb"
      - "!midterm-project/**/README.md"
  #workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "teen-addiction-prediction:${{ github.sha }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag Docker image for ECR
        run: |
          IMAGE_URI=${{ vars.ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Update App Runner Service
        run: |
          SERVICE_ARN=arn:aws:apprunner:${{ vars.AWS_REGION }}:${{ vars.ACCOUNT_ID }}:service/prediction-app/${{ secrets.APP_RUNNER}}
          aws apprunner update-service \
            --service-arn $SERVICE_ARN \
            --source-configuration ImageRepository="{ImageIdentifier=$IMAGE_URI,ImageRepositoryType=ECR}"